apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    name: api
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
      app: todolist
      environment: base
  template:
    metadata:
      labels:
        tier: backend
        app: todolist
        environment: base
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z postgres 5432; do
              echo "Waiting for PostgreSQL..."
              sleep 2
              done
      containers:
        - name: todolist-api
          image: todolist/api
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
          # livenessProbe:
          #   httpGet:
          #     path: /monitoring/health
          #     port: 5001
          #   initialDelaySeconds: 20
          #   periodSeconds: 10
          #   failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /monitoring/health
              port: 5001
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: DATABASE_URL
