apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api/api.yaml
  - api/api-service.yaml
  - database/db-service.yaml
  - database/db.yaml
  - database/db-pvc.yaml
  - database/db-pv.yaml
  - database-ui/adminer-deployment.yaml
  - database-ui/adminer-service.yaml
  - database-ui/nginx-ingress.yaml

commonLabels:
  app: todolist
  environment: base

commonAnnotations:
  description: 'TodoList API base configuration'
