apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    name: api
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: api
  template:
    metadata:
      labels:
        name: api
    spec:
      containers:
        - name: todolist-api
          image: todolist/api
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: DATABASE_URL
